name: GB Studio Web Export

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SuperMarioBrosMini project
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libnss3 libxss1 libasound2 libx11-xcb-dev libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libgbm1
          sudo apt-get install -y npm

      - name: Clone GB Studio (develop branch)
        run: |
          git clone --branch develop --depth 1 https://github.com/chrismaltby/gb-studio.git
          cd gb-studio
          npm install --legacy-peer-deps

      # Check directory structure to confirm successful clone
      - name: List files for inspection
        run: ls -R gb-studio || echo "gb-studio directory not found"

      # Attempt to use Electron with corrected paths
      - name: Attempt Headless Export for Web
        run: |
          if [ -d "gb-studio/dist" ]; then
            npx electron gb-studio/dist/app.js --build SuperMarioBrosMini --export web --output ./exported-web || echo "CLI export not found"
          else
            echo "Expected gb-studio/dist directory not found"
          fi

      # Alternative: Run the application directly if CLI fails
      - name: Export using GB Studio application if CLI fails
        run: |
          if [ -d "gb-studio" ]; then
            cd gb-studio
            npm run build  # Assuming 'build' generates the main application
            npx electron . --build ../SuperMarioBrosMini --export web --output ../exported-web || echo "Application export failed"
          else
            echo "gb-studio directory not found for application export"
          fi

      - name: Upload Web Export as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-export
          path: ./exported-web
