name: GB Studio Web Export

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SuperMarioBrosMini project
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libnss3 libxss1 libasound2 libx11-xcb-dev libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libgbm1
          sudo apt-get install -y npm

      - name: Clone GB Studio (develop branch)
        run: |
          git clone --branch develop --depth 1 https://github.com/chrismaltby/gb-studio.git
          cd gb-studio
          npm install --legacy-peer-deps
          cd ..

      # New step to list files and check for CLI alternatives
      - name: List GB Studio files for inspection
        run: ls -R gb-studio

      # Try the alternative CLI path or find the actual entry point
      - name: Export project for Web (if CLI is found)
        run: |
          # Adjust the path based on the correct CLI location found in the previous step
          node gb-studio/out/path_to_correct_cli.js build SuperMarioBrosMini --export web --output ./exported-web

      - name: Upload Web Export as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-export
          path: ./exported-web
