name: GB Studio Web Export

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout SuperMarioBrosMini project
        uses: actions/checkout@v3
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libnss3 libxss1 libasound2 libx11-xcb-dev libxcomposite1 libxcursor1 libxdamage1 libxrandr2 libgbm1
          sudo apt-get install -y npm

      - name: Clone GB Studio 4.2.0 Source
        run: |
          git clone --branch v4.2.0 --depth 1 https://github.com/chrismaltby/gb-studio.git
          cd gb-studio
          npm install
          npm run build
          cd ..

      - name: Export project for Web
        run: |
          node gb-studio/out/cli.js build SuperMarioBrosMini --export web --output ./exported-web

      - name: Upload Web Export as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-export
          path: ./exported-web
